### ISSUE TITLE
Require one meaningful comment

### ISSUE THREAD

**Issue by lacabra** [lacabra/validate-digitalpublicgoods#17]
Require at least one "meaningful comment" before the submission is processed to filter out submissions that don't add value.

The very basic and minimum implementation for this feature would be to check whether there is at least one non-empty comment field in the entire form, and prevent the user from submitting the form unless that requirement is met. The "non-empty" can be further enhanced with additional checks. We are open to suggestions on how to implement the requirement to be "meaningful".

**Comment by vaishnavi-ch** [comment]
@lacabra can I work on this issue?

**Comment by vaishnavi-ch** [comment]
@lacabra I have  [completed](https://github.com/lacabra/validate-digitalpublicgoods/compare/main...vaishnavi-ch:vaishnavi-ch-patch-3)  the first requirement i.e check whether there is at least one non-empty comment field in the entire form and prevent the user, Kindly let me know if it looks fine and the changes to be made. 
For the meaningful part, can u suggest some requirements for it?.

**Comment by lacabra** [comment]
Well, my only observation is that a meaningful comment has to have a minimum length that is significantly longer than 0. For example if someone says `Yes`, the length matches your check of being greater than 0, but that is not meaningful; so I would pick up a threshold of minimum length that is greater than the current 0. But beyond that I agree it is very hard to assess meaningfulness programatically. Set that predefined length as a constant towards the top of the file so that we can modify it easily in the future.
