### ISSUE TITLE
Add GitHub actions to enforce code style

### ISSUE THREAD

**Issue by lacabra** [lacabra/validate-digitalpublicgoods#18]
As a continuation of the work started in #14, configure the CI through GitHub Actions to enforce the code style upon committing files to the repo.

**Comment by DivyanshiSingh** [comment]
Hey @lacabra please assign this issue to me.

**Comment by DivyanshiSingh** [comment]
Can you describe more about this issue @lacabra. It would be a great help for me to resolve this issue.

**Comment by lacabra** [comment]
@DivyanshiSingh: Absolutely. Right now there is a [precommit hook](https://github.com/lacabra/validate-digitalpublicgoods/blob/48ba60aad4e90763d71024ad864c2182bc01e93f/package.json#L80) that checks that all the code files follow a coding standard to ensure consistency (especially important when multiple people contribute to a code repository and may use different coding styles), for background, read more about [git hooks](https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks).

Still it could be that some developer did not configure the git hook properly, or intentionally bypassed it, and pushed some changes that did not match the agreed code style. To address this possibility, I am hereby looking to run this check as part of the CI, which will succeed if the linter passes, or will fail otherwise. For a reference implementation see [this line](https://github.com/unicef/publicgoods-candidates/blob/9e04ee7d3e94a0849a0af13aa9416acc7ddf0824/.github/workflows/main.yml#L18) on this other repo (where you worked recently 😉) which does what I am requesting here. The catch is that the CI is not yet set up on this repo, so you need to add the file (please name it `.github/workflows/main.yml`) that contains the requested check.
